### Get all words
GET http://localhost:5161/words

### Get specific word
GET http://localhost:5161/words/日本

### Get nonexistent word
GET http://localhost:5161/words/foo

### Get total word count
GET http://localhost:5161/words/count

### Get count of words known 90% or more
GET http://localhost:5161/words/count?min=0.9
