### Queries

### Get all words
GET http://localhost:5161/words/all

### Get specific word
GET http://localhost:5161/words?value=単語

### Get nonexistent word
GET http://localhost:5161/words?value=foo

### Get total word count
GET http://localhost:5161/words/count

### Get count of words known 90% or more
GET http://localhost:5161/words/count?min=0.9

### Get a custom source
GET http://localhost:5161/sources/custom?value=単語

### Get WaniKani source
GET http://localhost:5161/sources/wanikani?value=口


### Add a custom source
POST http://localhost:5161/sources/custom
Content-Type: application/json

{"value": "単語", "kf": 0.8}

